# Generated by Django 3.0.5 on 2022-09-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='passwor',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='usernam',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
