# Generated by Django 3.0.5 on 2022-09-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0005_auto_20220905_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogg',
            name='passwor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blogg',
            name='usernam',
            field=models.CharField(max_length=100),
        ),
    ]
