# Generated by Django 3.0.5 on 2022-09-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0006_auto_20220905_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/CustomerProfilePic/'),
        ),
    ]
