# Generated by Django 3.2.15 on 2022-10-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0016_auto_20220921_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='billmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daySpent', models.PositiveIntegerField()),
                ('roomCharge', models.PositiveIntegerField()),
                ('cost', models.PositiveIntegerField()),
                ('bFee', models.PositiveIntegerField()),
                ('otherCharge', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
            ],
        ),
    ]
