# Generated by Django 3.2.15 on 2022-10-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0017_billmount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billmount',
            name='bFee',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='billmount',
            name='cost',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='billmount',
            name='daySpent',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='billmount',
            name='otherCharge',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='billmount',
            name='roomCharge',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='billmount',
            name='total',
            field=models.IntegerField(max_length=100),
        ),
    ]
